package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/sts"
	"github.com/aws/aws-sdk-go-v2/service/sts/types"
	"github.com/pquerna/otp/totp"
)

var TOTP = os.Getenv("TOTP_SECRET")

type OutputCredentials struct {
	AWSAccessKeyID     string
	AWSSecretAccessKey string
	Expiration         time.Time
	AWSSessionToken    string
}

func FromCredentials(c *types.Credentials) *OutputCredentials {
	o := new(OutputCredentials)
	o.AWSAccessKeyID = *c.AccessKeyId
	o.AWSSecretAccessKey = *c.SecretAccessKey
	o.Expiration = *c.Expiration
	o.AWSSessionToken = *c.SessionToken
	return o
}

func (o *OutputCredentials) ToMap() map[string]string {
	return map[string]string{
		"aws_access_key_id":     o.AWSAccessKeyID,
		"aws_secret_access_key": o.AWSSecretAccessKey,
		"aws_session_token":     o.AWSSessionToken,
	}
}

func (o *OutputCredentials) ToINI(prefix string) string {
	if prefix == "" {
		prefix = "mfa"
	}
	m := o.ToMap()
	sb := new(strings.Builder)
	sb.WriteString("; start of autogenerated section by mufasa, do not edit manually!\n")
	sb.WriteString(fmt.Sprintf("[%s]\n", prefix))
	for k, v := range m {
		sb.WriteString(fmt.Sprintf("%s = %s\n", k, v))
	}
	sb.WriteString("; end of autogenerated section by mufasa\n")
	return sb.String()
}

func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO())
	if err != nil {
		log.Fatal(err)
	}
	svc := sts.NewFromConfig(cfg)
	identity, err := svc.GetCallerIdentity(context.TODO(), nil)
	if err != nil {
		log.Fatal(err)
	}
	mfa := strings.Replace(*identity.Arn, "user", "mfa", 1)
	otp, err := totp.GenerateCode(TOTP, time.Now())
	if err != nil {
		log.Fatal(err)
	}
	duration := (int32)((12 * time.Hour).Seconds())
	token, err := svc.GetSessionToken(context.TODO(), &sts.GetSessionTokenInput{
		SerialNumber:    &mfa,
		TokenCode:       &otp,
		DurationSeconds: &duration,
	})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(FromCredentials(token.Credentials).ToINI(""))
}
